apiVersion: apps/v1
kind: Deployment
metadata:
 name: blue
spec:
 replicas: 3
 selector:
  matchLabels:
    name: blue
 template:
  metadata:
   labels:
    name: blue
  spec:
   containers:
    - image: nginx
      name: blue