apiVersion: apps/v1
kind: Deployment
metadata:
 name: red
spec:
 replicas: 2
 selector:
   matchLabels:
     name: red
 template:
   metadata:
     labels:
       name: red
   spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
               - key: node-role.kubernetes.io/control-plane
                 operator: Exists
      containers:
       - image: nginx
         name: red