apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-21T15:41:57Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "900"
  uid: b920d81a-0922-4ae9-a0fa-af8532424e8b
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
     - secretRef:
        name: db-secret