apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  selector: 
    matchLabels:
      app: myapp-deployment
  template: 
    metadata:
      name: nginx
      labels:
        app: myapp-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        env:
          - name: GREETING
            value: "Warm greeting to you"
  replicas: 3
