apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2024-05-19T15:04:26Z"
  generation: 1
  name: new-replica-set
  namespace: default
  resourceVersion: "987"
  uid: 9783913d-2bb5-4fda-b3c6-47abbbbb4a99
spec:
  replicas: 5
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: Always
        name: busybox-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 4
  observedGeneration: 1
  replicas: 4