apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-21T16:12:53Z"
  name: red
  namespace: default
  resourceVersion: "835"
  uid: 8330a5d5-2d24-43dc-877a-89fd642dacbc
spec:
  initContainers:
  - name: one
    image: busybox
    command: ["sleep", "20"]
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-shgdp
      readOnly: true